on:
  push:
    tags:
      - v**

jobs:
  build-and-upload:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.17'
      - name: Go Build
        run: |
          GOOS=linux GOARCH=amd64 go build -o ./build/tflow-linux-amd64
          GOOS=darwin GOARCH=amd64 go build -o ./build/tflow-osx-amd64
          GOOS=windows GOARCH=amd64 go build -o ./build/tflow-windows-amd64.exe

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./build/*
          tag: ${{ github.ref }}
          overwrite: true
          prerelease: true
          file_glob: true
          body: "Release ${{ github.ref }}"
